In [5]:
import numpy as np

In [6]:
my_list = list(range(1, 10))
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
my_array = np.arange(1, 10)
my_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.zeros(9)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [9]:
np.ones((3, 3), dtype=float)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [17]:
# depth, rows, columns
x = np.ones((3, 4, 2), dtype=int)

In [19]:
print(x)

[[[1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]]]


In [20]:
np.full((2, 2), 9.7)

array([[ 9.7,  9.7],
       [ 9.7,  9.7]])

In [21]:
np.random.normal(0, 1, (3, 2))

array([[-0.40304252, -0.25877778],
       [-0.67297122,  0.21732099],
       [ 0.7413568 , -0.60149373]])

In [23]:
# Identity matrix
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [26]:
x = np.array([2, 7, 28, 34, 27, 99, 6])
x

array([ 2,  7, 28, 34, 27, 99,  6])

In [27]:
x[2]

28

In [28]:
x[-2]

99

In [29]:
x[4:]

array([27, 99,  6])

In [31]:
x[3:6]

array([34, 27, 99])

In [32]:
y = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
y[0, 1]

2

In [36]:
z = y[1]
z

array([5, 6, 7, 8])

In [41]:
y[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
y[:, [1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [46]:
y[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [50]:
y[1:4, 2:4]

array([[ 7,  8],
       [11, 12]])

In [51]:
y[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [53]:
list_a = [1, 2, 3]
list_b = [4, 5, 6]

arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

In [54]:
list_a + list_b

[1, 2, 3, 4, 5, 6]

In [55]:
arr_a + arr_b

array([5, 7, 9])

In [58]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [57]:
np.multiply(x, y)

array([[ 5, 12],
       [21, 32]])

In [59]:
np.dot(x, y)

array([[19, 22],
       [43, 50]])

In [61]:
# Adds all elements to get the mean
print(x)
x.mean()

[[1 2]
 [3 4]]


2.5

In [62]:
# Gets the means of the columns
x.mean(axis=0)

array([ 2.,  3.])

In [63]:
# Gets the means of the rows
x.mean(axis=1)

array([ 1.5,  3.5])